apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-demo
  template:
    metadata:
      labels:
        app: busybox-demo
    spec:
      containers:
      - name: busybox
        image: busybox:1.32  # Change this tag to trigger Argo deployments
        command: ['sh', '-c', 'echo "BusyBox running" && sleep 3600']
